### ISSUE TITLE
Does not run 

### ISSUE THREAD

**Issue by brandsmill** [subwaymatch/nextjs-with-sqljs-example#1]
Nice...  However, I tried to run the demo on Vercel but I encountered some issues ..just showing loading... . I am not sure if I have missed something or if there is a problem with the demo itself. ... maybe needs an update

**Comment by christopher-caldwell** [comment]
@brandsmill 
I pulled this down and added a try catch, it seems to be erroring on the instantiation `new SQL.Database()` :
> e._RegisterExtensionFunctions.apply is not a function
    at e._RegisterExtensionFunctions (sql-wasm.js:171:437)
    at new c (sql-wasm.js:79:207)
    at eval (index.js:22:23)

I haven't been able to make this lib work with Next. Not a fun experience so far.
